### ISSUE TITLE
Can I run a simulation using this code

### ISSUE THREAD

**Issue by suoigwg** [coins-lab/relaxed_astar#2]
Hi there 
    I followed the instructions in this [post](http://www.iroboapp.org/index.php?title=Adding_Relaxed_Astar_Global_Path_Planner_As_Plugin_in_ROS) 
But when I ran 
`roslaunch turtlebot_rviz_launchers view_navigation.launch --screen`
I got this
<img width="1309" alt="screen shot 2017-06-09 at 7 11 17 pm" src="https://user-images.githubusercontent.com/15700090/26973355-b1b49314-4d48-11e7-84eb-8f81083d90ba.png">

What could possibly be wrong?
btw: I am using kinetic

**Comment by iroboapp** [comment]
Hi suoigwg,
Are you working with simulator or with real robot?
Can you capture or copy the error message appear in the terminal.

**Comment by suoigwg** [comment]
I am using the simulator
I change the move_base_xml.launch  to as follows

`
<launch>
  <include file="$(find turtlebot_navigation)/launch/includes/velocity_smoother.launch.xml"/>
  <include file="$(find turtlebot_navigation)/launch/includes/safety_controller.launch.xml"/>
  
  <arg name="odom_frame_id"   default="odom"/>
  <arg name="base_frame_id"   default="base_footprint"/>
  <arg name="global_frame_id" default="map"/>
  <arg name="odom_topic" default="odom" />
  <arg name="laser_topic" default="scan" />
  <arg name="custom_param_file" default="$(find turtlebot_navigation)/param/dummy.yaml"/>

  <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">
    <rosparam file="$(find turtlebot_navigation)/param/costmap_common_params.yaml" command="load" ns="global_costmap" />
    <rosparam file="$(find turtlebot_navigation)/param/costmap_common_params.yaml" command="load" ns="local_costmap" />   
    <rosparam file="$(find turtlebot_navigation)/param/local_costmap_params.yaml" command="load" />   
    <rosparam file="$(find turtlebot_navigation)/param/global_costmap_params.yaml" command="load" />
    <rosparam file="$(find turtlebot_navigation)/param/dwa_local_planner_params.yaml" command="load" />
    <rosparam file="$(find turtlebot_navigation)/param/move_base_params.yaml" command="load" />
    <rosparam file="$(find turtlebot_navigation)/param/global_planner_params.yaml" command="load" />
    <rosparam file="$(find turtlebot_navigation)/param/navfn_global_planner_params.yaml" command="load" />
    
    <rosparam file="$(arg custom_param_file)" command="load" />
    
    
    <param name="global_costmap/global_frame" value="$(arg global_frame_id)"/>
    <param name="global_costmap/robot_base_frame" value="$(arg base_frame_id)"/>
    <param name="local_costmap/global_frame" value="$(arg odom_frame_id)"/>
    <param name="local_costmap/robot_base_frame" value="$(arg base_frame_id)"/>
    <param name="DWAPlannerROS/global_frame_id" value="$(arg odom_frame_id)"/>
    <param name="base_global_planner" value="RAstar_planner/RAstarPlannerROS"/> 


    <remap from="cmd_vel" to="navigation_velocity_smoother/raw_cmd_vel"/>
    <remap from="odom" to="$(arg odom_topic)"/>
    <remap from="scan" to="$(arg laser_topic)"/>
  </node>
</launch>`

Here is what is in the terminal

`aunch turtlebot_rviz_launchers view_navigation.launch --screen
... logging to /home/yisheng/.ros/log/3e526808-4d87-11e7-9a68-000c29b5f232/roslaunch-ubuntu-3413.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:35479/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [3425]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 3e526808-4d87-11e7-9a68-000c29b5f232
process[rosout-1]: started with pid [3438]
started core service [/rosout]
process[rviz-2]: started with pid [3441]
[ INFO] [1497062892.809160044]: rviz version 1.12.4
[ INFO] [1497062892.809231581]: compiled against Qt version 5.5.1
[ INFO] [1497062892.809261002]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1497062893.629463384]: Stereo is NOT SUPPORTED
[ INFO] [1497062893.629555811]: OpenGl version: 2.1 (GLSL 1.2).

`

**Comment by suoigwg** [comment]
btw I am on kinetic ubuntu 14.04

**Comment by suoigwg** [comment]
> 3- You must now bringup your turtlebot. You need to launch minimal.launch, 3dsensor.launch, amcl.launch.xml and move_base.launch.xml. Here is an example of launch file that can be used for this purpose.
<launch>
<include file="$(find turtlebot_bringup)/launch/minimal.launch"></include>

  <include file="$(find turtlebot_bringup)/launch/3dsensor.launch">
    <arg name="rgb_processing" value="false" />
    <arg name="depth_registration" value="false" />
    <arg name="depth_processing" value="false" />
    <arg name="scan_topic" value="/scan" />
  </include>

  <arg name="map_file" default="map_folder/your_map_file.yaml"/>
  <node name="map_server" pkg="map_server" type="map_server" args="$(arg map_file)" />

  <arg name="initial_pose_x" default="0.0"/>
  <arg name="initial_pose_y" default="0.0"/>
  <arg name="initial_pose_a" default="0.0"/>
  <include file="$(find turtlebot_navigation)/launch/includes/amcl.launch.xml">
    <arg name="initial_pose_x" value="$(arg initial_pose_x)"/>
    <arg name="initial_pose_y" value="$(arg initial_pose_y)"/>
    <arg name="initial_pose_a" value="$(arg initial_pose_a)"/>
  </include>

  <include file="$(find turtlebot_navigation)/launch/includes/move_base.launch.xml"/>

</launch>
Note that changes made in the file move_base.launch.xml will now be considered when you bring-up your turtlebot with this launch file.

I am a bit confused here. Do I need to create a new launch file or just change _turtlebot_rviz_launchers view_navigation.launch_ , I am doing the latter

Thanks for your time and help!

**Comment by suoigwg** [comment]
also I saw nothing in rqt_graph.
Did I miss anything?

**Comment by iroboapp** [comment]
Hi suoigwg, 

You should bringup your robot before running this command: roslaunch turtlebot_rviz_launchers view_navigation.launch --screen

One possible option here is to use launch file from Stage Simulator to bring up your simulated turtlebot http://wiki.ros.org/turtlebot_stage/Tutorials/indigo/Bring%20up%20TurtleBot%20in%20stage

**Comment by suoigwg** [comment]
Thanks 
I do find it works
However, I still can't find the move_base/ /global_plan
which step could I did wrong?
<img width="1161" alt="screen shot 2017-06-10 at 11 30 36 am" src="https://user-images.githubusercontent.com/15700090/26999623-f17d447c-4dd0-11e7-8e95-299f3138fcf5.png">

**Comment by suoigwg** [comment]
I thought it could be the `move_base.launch.xml`

but I have double checked it.

**Comment by suoigwg** [comment]
Isn't everything before

> Running the Plugin on the Turtlebot

in the [post](http://www.iroboapp.org/index.php?title=Adding_Relaxed_Astar_Global_Path_Planner_As_Plugin_in_ROS) has already been done in this repo?

**Comment by iroboapp** [comment]
Did you add move_base.launch.xml directory to your launch file?
If you use same directories as in the tutorial you may add this line:
`<include file="$(find turtlebot_navigation)/launch/includes/move_base.launch.xml"/>`
to your launch file.

**Comment by suoigwg** [comment]
Below is my launch file 

`<launch>
<include file="$(find turtlebot_bringup)/launch/minimal.launch"></include>

  <include file="$(find turtlebot_bringup)/launch/3dsensor.launch">
    <arg name="rgb_processing" value="false" />
    <arg name="depth_registration" value="false" />
    <arg name="depth_processing" value="false" />
    <arg name="scan_topic" value="/scan" />
  </include>

  <arg name="map_file" default="/home/yisheng/ros_workspace/src/Robot-Motion-Planning-in-ROS-Kinetic
/FinalMap.yaml"/>
  <node name="map_server" pkg="map_server" type="map_server" args="$(arg map_file)" />

  <arg name="initial_pose_x" default="0.0"/>
  <arg name="initial_pose_y" default="0.0"/>
  <arg name="initial_pose_a" default="0.0"/>
  <include file="$(find turtlebot_navigation)/launch/includes/amcl.launch.xml">
    <arg name="initial_pose_x" value="$(arg initial_pose_x)"/>
    <arg name="initial_pose_y" value="$(arg initial_pose_y)"/>
    <arg name="initial_pose_a" value="$(arg initial_pose_a)"/>
  </include>

  <include file="$(find turtlebot_navigation)/launch/includes/move_base.launch.xml"/>

</launch>`

When I tried to launch it with `roslaunch relaxed_astar ast.launch`

**Comment by iroboapp** [comment]
In rviz, can you see the other parameters of move_base?

**Comment by suoigwg** [comment]
I suppose no
<img width="1161" alt="screen shot 2017-06-10 at 11 30 36 am" src="https://user-images.githubusercontent.com/15700090/27000326-8fc38f00-4de1-11e7-893c-91597e0c4050.png">

**Comment by iroboapp** [comment]
Can you put the move_base_xml.launch file complete content.

**Comment by suoigwg** [comment]
```
<!-- 
    ROS navigation stack with velocity smoother and safety (reactive) controller
-->
<launch>
  <include file="$(find turtlebot_navigation)/launch/includes/velocity_smoother.launch.xml"/>
  <include file="$(find turtlebot_navigation)/launch/includes/safety_controller.launch.xml"/>
  
  <arg name="odom_frame_id"   default="odom"/>
  <arg name="base_frame_id"   default="base_footprint"/>
  <arg name="global_frame_id" default="map"/>
  <arg name="odom_topic" default="odom" />
  <arg name="laser_topic" default="scan" />
  <arg name="custom_param_file" default="$(find turtlebot_navigation)/param/dummy.yaml"/>

  <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">
    <rosparam file="$(find turtlebot_navigation)/param/costmap_common_params.yaml" command="load" ns="global_costmap" />
    <rosparam file="$(find turtlebot_navigation)/param/costmap_common_params.yaml" command="load" ns="local_costmap" />   
    <rosparam file="$(find turtlebot_navigation)/param/local_costmap_params.yaml" command="load" />   
    <rosparam file="$(find turtlebot_navigation)/param/global_costmap_params.yaml" command="load" />
    <rosparam file="$(find turtlebot_navigation)/param/dwa_local_planner_params.yaml" command="load" />
    <rosparam file="$(find turtlebot_navigation)/param/move_base_params.yaml" command="load" />
    <rosparam file="$(find turtlebot_navigation)/param/global_planner_params.yaml" command="load" />
    <rosparam file="$(find turtlebot_navigation)/param/navfn_global_planner_params.yaml" command="load" />
    <!-- external params file that could be loaded into the move_base namespace -->
    <rosparam file="$(arg custom_param_file)" command="load" />
    
    <!-- reset frame_id parameters using user input data -->
    <param name="global_costmap/global_frame" value="$(arg global_frame_id)"/>
    <param name="global_costmap/robot_base_frame" value="$(arg base_frame_id)"/>
    <param name="local_costmap/global_frame" value="$(arg odom_frame_id)"/>
    <param name="local_costmap/robot_base_frame" value="$(arg base_frame_id)"/>
    <param name="DWAPlannerROS/global_frame_id" value="$(arg odom_frame_id)"/>
    <param name="base_global_planner" value="RAstar_planner/RAstarPlannerROS"/> 


    <remap from="cmd_vel" to="navigation_velocity_smoother/raw_cmd_vel"/>
    <remap from="odom" to="$(arg odom_topic)"/>
    <remap from="scan" to="$(arg laser_topic)"/>
  </node>
</launch>
```

**Comment by iroboapp** [comment]
What is the output of the command `$rosnode list `

**Comment by suoigwg** [comment]
when I run `roslaunch turtlebot_rviz_launchers view_navigation.launch --screen`
/rosout
/rviz

**Comment by iroboapp** [comment]
Bring up your robot first, then run `$roslaunch turtlebot_rviz_launchers view_navigation.launch --screen`
Then check the output for `$rosnode list` again

**Comment by suoigwg** [comment]
I first tried  `roslaunch turtlebot_stage turtlebot_in_stage.launch`
then `roslaunch turtlebot_rviz_launchers view_navigation.launch --screen`

`rosnode list`

the output is
```
/amcl
/cmd_vel_mux
/diagnostic_aggregator
/joint_state_publisher
/kobuki_safety_controller
/map_server
/mobile_base_nodelet_manager
/navigation_velocity_smoother
/robot_state_publisher
/rosout
/rviz
/stageros

```

**Comment by iroboapp** [comment]
You have to make sure that move_base is properly installed and working on your machine.
